name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # 1. Static Analysis - Checkstyle
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adoptopenjdk'  # or another distribution if needed

      - name: Run Checkstyle
        run: mvn checkstyle:check

  # 2. Unit Tests & Coverage (Jacoco)
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adoptopenjdk'  # or another distribution if needed

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Unit Test
        run: |
          mvn test
