name: Pull Request Validation

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17

      # 3. Install dependencies and build project
      - name: Build with Maven
        run: mvn clean install

      # 4. Run Checkstyle to ensure code style compliance
      - name: Run Checkstyle
        run: mvn checkstyle:check

      # 5. Run unit tests
      - name: Run Unit Tests
        run: mvn test

      # 6. Check test coverage (ensure JaCoCo plugin is configured in pom.xml)
      - name: Ensure Test Coverage
        run: |
          mvn jacoco:report
          grep -q "coverage.*>90" target/site/jacoco/index.html || exit 1

      # 7. Run Performance Tests (assumes performance tests are defined in the project)
      - name: Run Performance Tests
        run: mvn test -Dtest=PerformanceTests

      # 8. Perform static application security testing (SAST) using Semgrep
      - name: Run Semgrep SAST
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
