name: Main Branch Workflow

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # 3. Build the project and install dependencies
      - name: Build with Maven
        run: mvn clean install

      # 4. Publish the package to GitHub Maven Registry
      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn deploy

      # 5. Generate Javadoc and deploy it to GH Pages
      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Deploy Javadoc to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
          destination_dir: javadoc/${{ github.run_number }}

      # 6. Generate Cobertura report and deploy it to GH Pages
      - name: Generate Cobertura Report
        run: |
          mvn cobertura:cobertura
          mkdir -p target/site/cobertura
          cp -r target/site/cobertura ./cobertura

      - name: Deploy Cobertura to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cobertura
          destination_dir: cobertura/${{ github.run_number }}
