name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # 1. Static Analysis - Checkstyle
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java 21 (Adoptium Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify repository structure
        run: ls -l

      - name: Run Checkstyle
        run: mvn checkstyle:check

  # 2. Unit Tests & Coverage
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java 21 (Adoptium Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Unit Test
        run: |
          mvn test
