name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # 1. Static Analysis - Checkstyle
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java 21 (Adoptium Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify repository structure
        run: ls -l

      - name: Run Checkstyle
        run: mvn checkstyle:check

  # 2. Unit Tests & Coverage
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java 21 (Adoptium Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Unit Test
        run: mvn test

  # 3. Build and Deploy to GitHub Maven Registry
  deploy_maven:
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - name: Set up Java 21 (Adoptium Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Maven Registry
        run: mvn deploy -DskipTests
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         GITHUB_USERNAME: ${{ github.actor }}

  # 4. Deploy Documentation using GitHub Pages
  deploy_docs:
    runs-on: ubuntu-latest
    needs: deploy_maven
    steps:
      - name: Set up Java 21 (Adoptium Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Deploy Javadoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          target_branch: gh-pages
          jekyll: false
          folder: target/site/apidocs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
